#cloud-config
package_update: true
package_upgrade: true

packages:
  - nginx
  - nmap

users:
  - name: web
    primary_group: web
    groups: [sudo]
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINzRnKu1hDMP7RmmFNpKjSqWcCxRn1Wo8Yql4UWrwZrW wk4

runcmd:
  - systemctl enable nginx
  - systemctl start nginx

